
- name: Test if SNMP MIBS directory exists
  stat:
    path:  '{{ snmp_mibs__mibs_directory }}'
  register: _snmp_mibs__mibs_directory

- name: Fail if SNMP MIBS directory is absent
  fail:
    msg: Missing mibs system directory
  when: (not _snmp_mibs__mibs_directory.stat.exists) or
        (not _snmp_mibs__mibs_directory.stat.isdir|d(False))
 
- name: Copy SNMP MIBS files
  copy:
    src:   'mibs/{{ item }}/'
    dest:  '{{ snmp_mibs__mibs_directory }}'
    owner: root
    group: root
    mode:  0644
  with_items: '{{ snmp_mibs__install_sets }}'
